### ISSUE TITLE
how to know the state of the checkbox in the onClick event handler

### ISSUE THREAD

**Issue by sballesteros** [scienceai/paper-checkbox#2]
as paper checkbox doesn't rely on an input, we can't check `e.target.checked`.
What's the best way to know if the checkbox is checked or not?
is it to rely on the aria attribute ? or is it to do smtg like:

``` js
<PaperCheckbox
  theme='light'
  id={facet.id}
  checked={facet.checked}
  onClick={this.handleClick.bind(this, facet.id, !facet.checked)} // to know if checked
>
```

**Comment by callahanchris** [comment]
This component relies on the parent component controlling its state (checked vs unchecked) and passing this state down via props. A good example is in the [test file](https://github.com/scienceai/paper-checkbox/blob/76a295c199fba19cea1caf372c9c5b6fa498014e/test/test.js#L49-L65). For CSS, we can target the `aria-checked` attribute with a selector such as `.paper-checkbox [aria-checked="true"] .checkbox`.

I'm not sure if adding an `e.target.checked` value to the event propagated up to the parent is necessary given that the parent always needs to be aware of the state of the `<PaperCheckbox>` it is rendering. FWIW the Polymer implementation does not seem to mock this behavior (see [here](https://github.com/PolymerElements/paper-checkbox/blob/master/paper-checkbox.html) and [here](https://github.com/PolymerElements/paper-behaviors/blob/master/paper-checked-element-behavior.html)).

**Comment by sballesteros** [comment]
thanks!
